Traceback (most recent call last):
  File "xweat/weat.py", line 15, in <module>
    import xweat.utils as utils
ModuleNotFoundError: No module named 'xweat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xweat/weat.py", line 17, in <module>
    import utils
  File "/home/v1rmuoz2/embedding_bias/scripts/xweat/utils.py", line 8, in <module>
    from nltk.corpus import stopwords
ModuleNotFoundError: No module named 'nltk'
